version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: narnaja_gym
      POSTGRES_USER: root
  web:
    build: .
    command: bundle exec rails s -p 5000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://root:123456@db/narnaja_gym
