# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # Configura el host, username y password para usar variables de entorno
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || '12345' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: gimnasio_narnaja

# Asegúrate de tener una configuración para test si la necesitas
test:
  <<: *default
  database: gimnasio_narnaja_test

production:
  <<: *default
  # Utiliza DATABASE_URL para configurar la base de datos en producción, si está disponible
  url: <%= ENV['DATABASE_URL'] %>
  # O configura individualmente host, database, etc.
  # host: <%= ENV['DB_HOST'] %>
  # database: <%= ENV['DB_NAME'] %>
  # username: <%= ENV['DB_USERNAME'] %>
  # password: <%= ENV['DB_PASSWORD'] %>
